# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.widget_addr_new.ui'
#
# Created: Tue Nov 29 23:14:47 2011
#      by: pyside-uic 0.2.13 running on PySide 1.0.7
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_widgetAddr(object):
    def setupUi(self, widgetAddr):
        widgetAddr.setObjectName("widgetAddr")
        widgetAddr.resize(692, 570)
        self.gridLayout = QtGui.QGridLayout(widgetAddr)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_3 = QtGui.QSplitter(widgetAddr)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.treeAddr = QtGui.QTreeWidget(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeAddr.sizePolicy().hasHeightForWidth())
        self.treeAddr.setSizePolicy(sizePolicy)
        self.treeAddr.setMinimumSize(QtCore.QSize(200, 0))
        self.treeAddr.setAnimated(True)
        self.treeAddr.setObjectName("treeAddr")
        self.treeAddr.headerItem().setText(0, "1")
        self.treeAddr.header().setSortIndicatorShown(False)
        self.tableAddr = QtGui.QTableWidget(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableAddr.sizePolicy().hasHeightForWidth())
        self.tableAddr.setSizePolicy(sizePolicy)
        self.tableAddr.setObjectName("tableAddr")
        self.tableAddr.setColumnCount(0)
        self.tableAddr.setRowCount(0)
        self.gridLayout.addWidget(self.splitter_3, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textSearch = QtGui.QLineEdit(widgetAddr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textSearch.sizePolicy().hasHeightForWidth())
        self.textSearch.setSizePolicy(sizePolicy)
        self.textSearch.setObjectName("textSearch")
        self.horizontalLayout.addWidget(self.textSearch)
        self.buttonSearch = QtGui.QPushButton(widgetAddr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSearch.sizePolicy().hasHeightForWidth())
        self.buttonSearch.setSizePolicy(sizePolicy)
        self.buttonSearch.setMaximumSize(QtCore.QSize(60, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/images/magnifier.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSearch.setIcon(icon)
        self.buttonSearch.setObjectName("buttonSearch")
        self.horizontalLayout.addWidget(self.buttonSearch)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.checkPublic = QtGui.QCheckBox(widgetAddr)
        self.checkPublic.setAutoRepeat(False)
        self.checkPublic.setAutoExclusive(False)
        self.checkPublic.setTristate(False)
        self.checkPublic.setObjectName("checkPublic")
        self.horizontalLayout.addWidget(self.checkPublic)
        self.buttonImport = QtGui.QPushButton(widgetAddr)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/images/folder_user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonImport.setIcon(icon1)
        self.buttonImport.setObjectName("buttonImport")
        self.horizontalLayout.addWidget(self.buttonImport)
        self.buttonExport = QtGui.QPushButton(widgetAddr)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/images/page_excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonExport.setIcon(icon2)
        self.buttonExport.setObjectName("buttonExport")
        self.horizontalLayout.addWidget(self.buttonExport)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelTitle = QtGui.QLabel(widgetAddr)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.labelTitle.setFont(font)
        self.labelTitle.setStyleSheet("color: rgb(88, 88, 88);")
        self.labelTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.horizontalLayout_2.addWidget(self.labelTitle)
        self.toolCheckableTree = QtGui.QToolButton(widgetAddr)
        self.toolCheckableTree.setMinimumSize(QtCore.QSize(0, 0))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/images/chart_organisation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolCheckableTree.setIcon(icon3)
        self.toolCheckableTree.setCheckable(True)
        self.toolCheckableTree.setChecked(True)
        self.toolCheckableTree.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.toolCheckableTree.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolCheckableTree.setAutoRaise(True)
        self.toolCheckableTree.setArrowType(QtCore.Qt.NoArrow)
        self.toolCheckableTree.setObjectName("toolCheckableTree")
        self.horizontalLayout_2.addWidget(self.toolCheckableTree)
        self.toolColumns = QtGui.QToolButton(widgetAddr)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resources/images/table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolColumns.setIcon(icon4)
        self.toolColumns.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.toolColumns.setAutoRaise(True)
        self.toolColumns.setObjectName("toolColumns")
        self.horizontalLayout_2.addWidget(self.toolColumns)
        spacerItem1 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.buttonCreate = QtGui.QPushButton(widgetAddr)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resources/images/group_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonCreate.setIcon(icon5)
        self.buttonCreate.setObjectName("buttonCreate")
        self.horizontalLayout_2.addWidget(self.buttonCreate)
        self.horizontalLayout_2.setStretch(0, 1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(2, 1)

        self.retranslateUi(widgetAddr)
        QtCore.QMetaObject.connectSlotsByName(widgetAddr)

    def retranslateUi(self, widgetAddr):
        widgetAddr.setWindowTitle(QtGui.QApplication.translate("widgetAddr", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.treeAddr.setSortingEnabled(False)
        self.tableAddr.setSortingEnabled(True)
        self.buttonSearch.setText(QtGui.QApplication.translate("widgetAddr", "찾기", None, QtGui.QApplication.UnicodeUTF8))
        self.checkPublic.setToolTip(QtGui.QApplication.translate("widgetAddr", "다른 사람들과 공유합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkPublic.setText(QtGui.QApplication.translate("widgetAddr", "주소록공개", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonImport.setToolTip(QtGui.QApplication.translate("widgetAddr", "현재 엑셀97~2003 형식만 지원합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonImport.setText(QtGui.QApplication.translate("widgetAddr", "가져오기", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonExport.setToolTip(QtGui.QApplication.translate("widgetAddr", "준비중입니다..", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonExport.setText(QtGui.QApplication.translate("widgetAddr", "내보내기", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTitle.setText(QtGui.QApplication.translate("widgetAddr", "주소록에 대한 부가정보를 표시합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.toolCheckableTree.setToolTip(QtGui.QApplication.translate("widgetAddr", "왼쪽의 트리를 보여줍니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.toolCheckableTree.setText(QtGui.QApplication.translate("widgetAddr", "트리보기", None, QtGui.QApplication.UnicodeUTF8))
        self.toolColumns.setText(QtGui.QApplication.translate("widgetAddr", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonCreate.setText(QtGui.QApplication.translate("widgetAddr", "주소록추가", None, QtGui.QApplication.UnicodeUTF8))

