# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.widget_dialpad_new.ui'
#
# Created: Tue Nov 29 23:19:03 2011
#      by: pyside-uic 0.2.13 running on PySide 1.0.7
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(271, 242)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Widget.sizePolicy().hasHeightForWidth())
        Widget.setSizePolicy(sizePolicy)
        Widget.setMinimumSize(QtCore.QSize(0, 0))
        Widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtGui.QGridLayout(Widget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(5, 5, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridDigitsLayout = QtGui.QGridLayout()
        self.gridDigitsLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridDigitsLayout.setSpacing(3)
        self.gridDigitsLayout.setContentsMargins(0, -1, -1, -1)
        self.gridDigitsLayout.setObjectName("gridDigitsLayout")
        self.dtmf1 = QtGui.QPushButton(Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf1.sizePolicy().hasHeightForWidth())
        self.dtmf1.setSizePolicy(sizePolicy)
        self.dtmf1.setMinimumSize(QtCore.QSize(60, 40))
        self.dtmf1.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.dtmf1.setFont(font)
        self.dtmf1.setObjectName("dtmf1")
        self.gridDigitsLayout.addWidget(self.dtmf1, 0, 0, 1, 1)
        self.dtmf2 = QtGui.QPushButton(Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf2.sizePolicy().hasHeightForWidth())
        self.dtmf2.setSizePolicy(sizePolicy)
        self.dtmf2.setMinimumSize(QtCore.QSize(60, 40))
        self.dtmf2.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.dtmf2.setFont(font)
        self.dtmf2.setObjectName("dtmf2")
        self.gridDigitsLayout.addWidget(self.dtmf2, 0, 1, 1, 1)
        self.dtmf3 = QtGui.QPushButton(Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf3.sizePolicy().hasHeightForWidth())
        self.dtmf3.setSizePolicy(sizePolicy)
        self.dtmf3.setMinimumSize(QtCore.QSize(60, 40))
        self.dtmf3.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.dtmf3.setFont(font)
        self.dtmf3.setObjectName("dtmf3")
        self.gridDigitsLayout.addWidget(self.dtmf3, 0, 2, 1, 1)
        self.dtmf4 = QtGui.QPushButton(Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf4.sizePolicy().hasHeightForWidth())
        self.dtmf4.setSizePolicy(sizePolicy)
        self.dtmf4.setMinimumSize(QtCore.QSize(60, 40))
        self.dtmf4.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.dtmf4.setFont(font)
        self.dtmf4.setObjectName("dtmf4")
        self.gridDigitsLayout.addWidget(self.dtmf4, 1, 0, 1, 1)
        self.dtmf5 = QtGui.QPushButton(Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf5.sizePolicy().hasHeightForWidth())
        self.dtmf5.setSizePolicy(sizePolicy)
        self.dtmf5.setMinimumSize(QtCore.QSize(60, 40))
        self.dtmf5.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.dtmf5.setFont(font)
        self.dtmf5.setObjectName("dtmf5")
        self.gridDigitsLayout.addWidget(self.dtmf5, 1, 1, 1, 1)
        self.dtmf7 = QtGui.QPushButton(Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf7.sizePolicy().hasHeightForWidth())
        self.dtmf7.setSizePolicy(sizePolicy)
        self.dtmf7.setMinimumSize(QtCore.QSize(60, 40))
        self.dtmf7.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.dtmf7.setFont(font)
        self.dtmf7.setObjectName("dtmf7")
        self.gridDigitsLayout.addWidget(self.dtmf7, 2, 0, 1, 1)
        self.dtmf8 = QtGui.QPushButton(Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf8.sizePolicy().hasHeightForWidth())
        self.dtmf8.setSizePolicy(sizePolicy)
        self.dtmf8.setMinimumSize(QtCore.QSize(60, 40))
        self.dtmf8.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.dtmf8.setFont(font)
        self.dtmf8.setObjectName("dtmf8")
        self.gridDigitsLayout.addWidget(self.dtmf8, 2, 1, 1, 1)
        self.dtmf9 = QtGui.QPushButton(Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf9.sizePolicy().hasHeightForWidth())
        self.dtmf9.setSizePolicy(sizePolicy)
        self.dtmf9.setMinimumSize(QtCore.QSize(60, 40))
        self.dtmf9.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.dtmf9.setFont(font)
        self.dtmf9.setObjectName("dtmf9")
        self.gridDigitsLayout.addWidget(self.dtmf9, 2, 2, 1, 1)
        self.dtmfStar = QtGui.QPushButton(Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmfStar.sizePolicy().hasHeightForWidth())
        self.dtmfStar.setSizePolicy(sizePolicy)
        self.dtmfStar.setMinimumSize(QtCore.QSize(60, 40))
        self.dtmfStar.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.dtmfStar.setFont(font)
        self.dtmfStar.setObjectName("dtmfStar")
        self.gridDigitsLayout.addWidget(self.dtmfStar, 3, 0, 1, 1)
        self.dtmf0 = QtGui.QPushButton(Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf0.sizePolicy().hasHeightForWidth())
        self.dtmf0.setSizePolicy(sizePolicy)
        self.dtmf0.setMinimumSize(QtCore.QSize(60, 40))
        self.dtmf0.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.dtmf0.setFont(font)
        self.dtmf0.setObjectName("dtmf0")
        self.gridDigitsLayout.addWidget(self.dtmf0, 3, 1, 1, 1)
        self.dtmfPound = QtGui.QPushButton(Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmfPound.sizePolicy().hasHeightForWidth())
        self.dtmfPound.setSizePolicy(sizePolicy)
        self.dtmfPound.setMinimumSize(QtCore.QSize(60, 40))
        self.dtmfPound.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.dtmfPound.setFont(font)
        self.dtmfPound.setObjectName("dtmfPound")
        self.gridDigitsLayout.addWidget(self.dtmfPound, 3, 2, 1, 1)
        self.buttonDial = QtGui.QPushButton(Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDial.sizePolicy().hasHeightForWidth())
        self.buttonDial.setSizePolicy(sizePolicy)
        self.buttonDial.setMinimumSize(QtCore.QSize(70, 40))
        self.buttonDial.setMaximumSize(QtCore.QSize(70, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.buttonDial.setFont(font)
        self.buttonDial.setStyleSheet("color: rgb(0, 0, 127);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/images/phone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonDial.setIcon(icon)
        self.buttonDial.setObjectName("buttonDial")
        self.gridDigitsLayout.addWidget(self.buttonDial, 0, 3, 1, 1)
        self.buttonHangup = QtGui.QPushButton(Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonHangup.sizePolicy().hasHeightForWidth())
        self.buttonHangup.setSizePolicy(sizePolicy)
        self.buttonHangup.setMinimumSize(QtCore.QSize(70, 40))
        self.buttonHangup.setMaximumSize(QtCore.QSize(70, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.buttonHangup.setFont(font)
        self.buttonHangup.setStyleSheet("color: rgb(170, 0, 0);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/images/phone_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonHangup.setIcon(icon1)
        self.buttonHangup.setObjectName("buttonHangup")
        self.gridDigitsLayout.addWidget(self.buttonHangup, 1, 3, 1, 1)
        self.dtmf6 = QtGui.QPushButton(Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf6.sizePolicy().hasHeightForWidth())
        self.dtmf6.setSizePolicy(sizePolicy)
        self.dtmf6.setMinimumSize(QtCore.QSize(60, 40))
        self.dtmf6.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.dtmf6.setFont(font)
        self.dtmf6.setObjectName("dtmf6")
        self.gridDigitsLayout.addWidget(self.dtmf6, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.gridDigitsLayout, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 3, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelNumber = QtGui.QLabel(Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelNumber.sizePolicy().hasHeightForWidth())
        self.labelNumber.setSizePolicy(sizePolicy)
        self.labelNumber.setMinimumSize(QtCore.QSize(0, 30))
        self.labelNumber.setMaximumSize(QtCore.QSize(500, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setWeight(75)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(True)
        self.labelNumber.setFont(font)
        self.labelNumber.setStyleSheet("background-color: black; color:white")
        self.labelNumber.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.labelNumber.setMargin(0)
        self.labelNumber.setIndent(5)
        self.labelNumber.setObjectName("labelNumber")
        self.verticalLayout.addWidget(self.labelNumber)
        self.labelStatus = QtGui.QLabel(Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatus.sizePolicy().hasHeightForWidth())
        self.labelStatus.setSizePolicy(sizePolicy)
        self.labelStatus.setMinimumSize(QtCore.QSize(0, 26))
        self.labelStatus.setMaximumSize(QtCore.QSize(500, 26))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.labelStatus.setFont(font)
        self.labelStatus.setStyleSheet("background-color: black; color:lightgray")
        self.labelStatus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelStatus.setMargin(0)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout.addWidget(self.labelStatus)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QtGui.QApplication.translate("Widget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        Widget.setToolTip(QtGui.QApplication.translate("Widget", "타이틀바를 더블클릭 해보세요!\n"
"탈부착 및 자유롭게 이동이 가능합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.dtmf1.setText(QtGui.QApplication.translate("Widget", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.dtmf2.setText(QtGui.QApplication.translate("Widget", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.dtmf3.setText(QtGui.QApplication.translate("Widget", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.dtmf4.setText(QtGui.QApplication.translate("Widget", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.dtmf5.setText(QtGui.QApplication.translate("Widget", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.dtmf7.setText(QtGui.QApplication.translate("Widget", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.dtmf8.setText(QtGui.QApplication.translate("Widget", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.dtmf9.setText(QtGui.QApplication.translate("Widget", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.dtmfStar.setText(QtGui.QApplication.translate("Widget", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.dtmf0.setText(QtGui.QApplication.translate("Widget", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.dtmfPound.setText(QtGui.QApplication.translate("Widget", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDial.setText(QtGui.QApplication.translate("Widget", "통화", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonHangup.setText(QtGui.QApplication.translate("Widget", "끊기", None, QtGui.QApplication.UnicodeUTF8))
        self.dtmf6.setText(QtGui.QApplication.translate("Widget", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNumber.setToolTip(QtGui.QApplication.translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#383838;\">키보드로 조작해보세요!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#383838;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#383838;\">ESC : 모든 숫자 지우기</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#383838;\">Back Space : 숫자 하나씩 지우기</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#383838;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#383838;\">숫자입력이 안될 때도 ESC 를 누르세요^^</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNumber.setText(QtGui.QApplication.translate("Widget", "01055090072", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStatus.setText(QtGui.QApplication.translate("Widget", "초기화 중입니다..", None, QtGui.QApplication.UnicodeUTF8))

